version: "3.0"

services:
    db:
        container_name: "db"
        build:
    api:
        container_name: "api"
        build: .
        restart: always
        tty: true
        ports:
            - 8000:8000
